apiVersion: v1
kind: Secret
metadata:
  name: agents-secret
type: Opaque
data:
  OPENAI_API_KEY: c2stWkNuQ3ktNWZoQ1dqbjlOOWxjYkh4elF3Q2JIdXZ2RlNTTFlYaXV0T1hyVDNCbGJrRkowQl9DUi1GaEZUSmd5bmtQTEowSmZhazZ2YkI1cm84SjJmbzEwR3h3RUE=
  GROQ_API_KEY: Z3NrXzJ3NWFyQ2F6MzRUaDA2dkcyVUh6V0dkeWIzRllEcUR6T29aS0dSQ3ZxSkRNckhjMElyR3M=
