apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-agents-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jose-henry/QnA-Config.git
    targetRevision: HEAD
    path: HELM/my_agents
    chart: my_agents
    helm:
      releaseName: my-agents
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
