{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my_agents.fullname" . }}-secret
  labels:
    {{- include "my_agents.labels" . | nindent 4 }}
type: {{ .Values.secrets.type }}
data:
  {{- toYaml .Values.secrets.data | nindent 2 }}
{{- end }} 